# Generated by Django 5.2.17 on 2026-09-07 19:19

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("elections", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("declared_last_name", models.CharField(max_length=200)),
                ("declared_first_names", models.CharField(max_length=200)),
                ("declared_dob", models.CharField(blank=True, max_length=40)),
                ("email", models.EmailField(max_length=254)),
                (
                    "email_canonical",
                    models.EmailField(
                        help_text="Adresse en minuscules, sans autre normalisation (§3.3).",
                        max_length=254,
                    ),
                ),
                ("declared_on_honour", models.BooleanField(default=False)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending_email", "en attente de confirmation"),
                            ("pending_review", "en attente d'examen"),
                            ("active", "active"),
                            ("rejected", "rejetée"),
                        ],
                        default="pending_email",
                        max_length=20,
                    ),
                ),
                ("review_reason", models.TextField(blank=True)),
                ("voter_hash", models.BinaryField(blank=True, max_length=32, null=True)),
                (
                    "channel",
                    models.CharField(
                        choices=[("none", "aucun"), ("online", "en ligne"), ("paper", "papier")],
                        default="none",
                        max_length=10,
                    ),
                ),
                ("language", models.CharField(default="fr", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("reminder_sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "poll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="elections.poll",
                    ),
                ),
                (
                    "roll_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registrations",
                        to="elections.rollentry",
                    ),
                ),
            ],
            options={
                "verbose_name": "inscription",
                "verbose_name_plural": "inscriptions",
            },
        ),
        migrations.CreateModel(
            name="DuplicateAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("at", models.DateTimeField(auto_now_add=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                (
                    "poll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duplicate_attempts",
                        to="elections.poll",
                    ),
                ),
                (
                    "existing_registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duplicate_attempts",
                        to="registrations.registration",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="registration",
            index=models.Index(fields=["poll", "state"], name="registratio_poll_id_00bbdd_idx"),
        ),
        migrations.AddIndex(
            model_name="registration",
            index=models.Index(
                fields=["poll", "voter_hash"], name="registratio_poll_id_80f2d0_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="registration",
            constraint=models.UniqueConstraint(
                fields=("poll", "roll_entry"),
                condition=models.Q(roll_entry__isnull=False) & ~models.Q(state="rejected"),
                name="uniq_registration_poll_roll_entry",
            ),
        ),
        migrations.AddConstraint(
            model_name="registration",
            constraint=models.UniqueConstraint(
                fields=("poll", "email_canonical"),
                condition=~models.Q(channel="paper"),
                name="uniq_registration_poll_email",
            ),
        ),
    ]
