# Generated by Django 5.2.17 on 2026-09-23 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elections", "0012_inv6_early_opening"),
        ("registrations", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="registration",
            name="uniq_registration_poll_email",
        ),
        migrations.AddConstraint(
            model_name="registration",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    models.Q(("channel", "paper"), _negated=True),
                    models.Q(("email_canonical", ""), _negated=True),
                ),
                fields=("poll", "email_canonical"),
                name="uniq_registration_poll_email",
            ),
        ),
    ]
