# Generated by Django 5.2.17 on 2026-09-07 19:19

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("actor_label", models.CharField(blank=True, max_length=50)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("poll_created", "scrutin créé"),
                            ("poll_config_changed", "configuration modifiée"),
                            ("poll_state_changed", "transition d'état"),
                            ("poll_closes_at_extended", "clôture repoussée"),
                            ("roll_imported", "liste électorale importée"),
                            ("roll_snapshot_taken", "copie figée prise"),
                            ("registration_reviewed", "inscription examinée"),
                            (
                                "registration_duplicate",
                                "tentative de doublon d'inscription",
                            ),
                            (
                                "registration_ineligible",
                                "inscription refusée : type de liste non autorisé",
                            ),
                            ("paper_ballot_created", "bulletin papier saisi"),
                            ("paper_ballot_corrected", "bulletin papier rectifié"),
                            ("paper_ballot_deleted", "bulletin papier supprimé"),
                            ("paper_ballot_countersigned", "bulletin contresigné"),
                            ("channel_collision_override", "collision de canal forcée"),
                            ("closure_override", "clôture forcée"),
                            ("tally_run", "dépouillement effectué"),
                            ("tiebreak_entered", "tirage au sort physique saisi"),
                            ("results_published", "résultats publiés"),
                            ("role_assigned", "rôle attribué"),
                            ("role_revoked", "rôle retiré"),
                            ("audit_log_accessed", "journal consulté"),
                            ("retention_purge", "purge de rétention"),
                            ("job_refused", "tâche planifiée refusée"),
                        ],
                        max_length=40,
                    ),
                ),
                ("object_ref", models.CharField(blank=True, max_length=100)),
                ("before", models.JSONField(blank=True, default=dict)),
                ("after", models.JSONField(blank=True, default=dict)),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("name_divergence_accepted", "divergence de nom acceptée"),
                            ("name_divergence_refused", "divergence de nom refusée"),
                            ("no_roll_match", "aucune correspondance dans la liste"),
                            (
                                "ineligible_list_type",
                                "type de liste non autorisé pour ce scrutin",
                            ),
                            ("identity_confirmed_at_mairie", "identité confirmée en mairie"),
                            ("keying_error", "erreur de saisie"),
                            ("voter_request", "demande de l'électeur"),
                            ("duplicate_ballot", "bulletin en double"),
                            ("voted_online_already", "a déjà voté en ligne"),
                            ("countersign_unavailable", "contreseing indisponible"),
                            ("deadline_reached", "échéance atteinte"),
                            ("administrative_decision", "décision administrative"),
                            ("other", "autre"),
                        ],
                        max_length=40,
                    ),
                ),
                ("at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "événement d'audit",
                "verbose_name_plural": "journal d'audit",
                "ordering": ["-at"],
            },
        ),
    ]
