# Generated by Django 5.2.17 on 2026-09-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0004_alter_auditevent_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditevent",
            name="action",
            field=models.CharField(
                choices=[
                    ("poll_created", "scrutin créé"),
                    ("poll_config_changed", "configuration modifiée"),
                    ("option_image_added", "image de proposition ajoutée"),
                    ("option_image_removed", "image de proposition supprimée"),
                    ("poll_state_changed", "transition d'état"),
                    ("poll_closes_at_extended", "clôture repoussée"),
                    ("poll_withdrawn", "scrutin retiré"),
                    ("roll_imported", "liste électorale importée"),
                    ("roll_snapshot_taken", "copie figée prise"),
                    ("registration_reviewed", "inscription examinée"),
                    ("registration_duplicate", "tentative de doublon d'inscription"),
                    ("registration_ineligible", "inscription refusée : type de liste non autorisé"),
                    ("paper_ballot_created", "bulletin papier saisi"),
                    ("paper_ballot_corrected", "bulletin papier rectifié"),
                    ("paper_ballot_deleted", "bulletin papier supprimé"),
                    ("paper_ballot_countersigned", "bulletin contresigné"),
                    ("channel_collision_override", "collision de canal forcée"),
                    ("closure_override", "clôture forcée"),
                    ("tally_run", "dépouillement effectué"),
                    ("tiebreak_entered", "tirage au sort physique saisi"),
                    ("results_published", "résultats publiés"),
                    ("role_assigned", "rôle attribué"),
                    ("role_revoked", "rôle retiré"),
                    ("mail_settings_changed", "paramètres de messagerie modifiés"),
                    ("template_created", "modèle enregistré"),
                    ("template_renamed", "modèle renommé"),
                    ("template_deleted", "modèle supprimé"),
                    ("audit_log_accessed", "journal consulté"),
                    ("retention_purge", "purge de rétention"),
                    ("working_roll_purged", "liste de travail purgée"),
                    ("job_refused", "tâche planifiée refusée"),
                ],
                max_length=40,
            ),
        ),
    ]
