# SPDX-License-Identifier: 0BSD
# §6.5.4: `registration_link_resent`.
# Generated by Django 5.2.17 on 2026-09-23 21:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0011_sandbox_poll_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditevent",
            name="action",
            field=models.CharField(
                choices=[
                    ("poll_created", "scrutin créé"),
                    ("poll_config_changed", "configuration modifiée"),
                    ("poll_image_added", "image du scrutin ajoutée"),
                    ("poll_image_removed", "image du scrutin supprimée"),
                    ("poll_state_changed", "transition d'état"),
                    ("poll_closes_at_extended", "clôture repoussée"),
                    ("poll_withdrawn", "scrutin retiré"),
                    ("poll_deleted", "scrutin d'essai supprimé"),
                    ("preview_link_generated", "lien d'aperçu généré"),
                    ("preview_link_revoked", "lien d'aperçu révoqué"),
                    ("roll_imported", "liste électorale importée"),
                    ("roll_snapshot_taken", "copie figée prise"),
                    ("registration_reviewed", "inscription examinée"),
                    ("registration_link_resent", "lien de confirmation renvoyé"),
                    ("registration_duplicate", "tentative de doublon d'inscription"),
                    ("registration_ineligible", "inscription refusée : type de liste non autorisé"),
                    ("paper_ballot_created", "bulletin papier saisi"),
                    ("paper_ballot_corrected", "bulletin papier rectifié"),
                    ("paper_ballot_deleted", "bulletin papier supprimé"),
                    ("paper_ballot_countersigned", "bulletin contresigné"),
                    ("reconciliation_recorded", "rapprochement papier enregistré"),
                    ("closure_override", "clôture forcée"),
                    ("tally_run", "dépouillement effectué"),
                    ("tiebreak_entered", "tirage au sort physique saisi"),
                    ("results_published", "résultats publiés"),
                    ("role_assigned", "rôle attribué"),
                    ("role_revoked", "rôle retiré"),
                    ("mail_settings_changed", "paramètres de messagerie modifiés"),
                    ("commune_settings_changed", "paramètres de la commune modifiés"),
                    ("commune_branding_changed", "image de la commune ajoutée"),
                    ("commune_branding_removed", "image de la commune supprimée"),
                    ("template_created", "modèle enregistré"),
                    ("template_renamed", "modèle renommé"),
                    ("template_deleted", "modèle supprimé"),
                    ("audit_log_accessed", "journal consulté"),
                    ("retention_purge", "purge de rétention"),
                    ("working_roll_purged", "liste de travail purgée"),
                    ("job_refused", "tâche planifiée refusée"),
                ],
                max_length=40,
            ),
        ),
    ]
