# Generated by Django 5.2.17 on 2026-09-07 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("elections", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pollrole",
            name="poll",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roles",
                to="elections.poll",
            ),
        ),
        migrations.AddField(
            model_name="pollrole",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="poll_roles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="pollrole",
            constraint=models.UniqueConstraint(
                fields=("poll", "user", "role"), name="uniq_poll_user_role"
            ),
        ),
    ]
