# SPDX-License-Identifier: 0BSD
# Generated by Django 5.2.17 on 2026-09-09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Commune",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Tel qu'il doit apparaître sur les pages publiques et dans la notice.",
                        max_length=200,
                        verbose_name="nom de la commune",
                    ),
                ),
                (
                    "data_protection_referent",
                    models.CharField(
                        help_text="Personne ou service à qui les électeurs adressent leurs demandes d'accès, de rectification et d'effacement (R-13.2).",
                        max_length=200,
                        verbose_name="référent données personnelles",
                    ),
                ),
                (
                    "data_protection_contact",
                    models.CharField(
                        help_text="Adresse électronique ou postale, publiée dans la notice d'information.",
                        max_length=300,
                        verbose_name="contact du référent",
                    ),
                ),
            ],
            options={
                "verbose_name": "commune",
                "verbose_name_plural": "commune",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("id", 1)), name="commune_is_singleton"
                    )
                ],
            },
        ),
    ]
