# SPDX-License-Identifier: 0BSD
# Generated by Django 5.2.17 on 2026-09-11 07:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_commune"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailSettings",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("host", models.CharField(max_length=255, verbose_name="serveur SMTP")),
                ("port", models.PositiveIntegerField(default=587, verbose_name="port")),
                (
                    "encryption",
                    models.CharField(
                        choices=[
                            ("none", "aucun"),
                            ("starttls", "STARTTLS"),
                            ("ssl", "SSL/TLS implicite"),
                        ],
                        default="starttls",
                        max_length=10,
                        verbose_name="chiffrement",
                    ),
                ),
                (
                    "username",
                    models.CharField(blank=True, max_length=255, verbose_name="identifiant"),
                ),
                (
                    "password_encrypted",
                    models.TextField(blank=True, default="", verbose_name="mot de passe (chiffré)"),
                ),
                (
                    "from_email",
                    models.EmailField(
                        blank=True,
                        help_text="Laissez vide pour utiliser l'adresse par défaut du déploiement. Doit généralement correspondre au compte authentifié auprès du serveur.",
                        max_length=254,
                        verbose_name="adresse d'expédition",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="dernière modification"),
                ),
            ],
            options={
                "verbose_name": "paramètres de messagerie",
                "verbose_name_plural": "paramètres de messagerie",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("id", 1)), name="mail_settings_is_singleton"
                    )
                ],
            },
        ),
    ]
