# SPDX-License-Identifier: 0BSD
# Generated by Django 5.2.17 on 2026-09-12 11:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_mailsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="commune",
            name="public_base_url",
            field=models.CharField(
                blank=True,
                default="",
                help_text=(
                    "Ex. : https://votecommune.fr — sans barre oblique finale. Utilisée "
                    "pour composer les liens des courriels envoyés aux électeurs. Laissez "
                    "vide pour utiliser l'adresse configurée au déploiement."
                ),
                max_length=200,
                verbose_name="adresse du site",
            ),
        ),
    ]
