# SPDX-License-Identifier: 0BSD
# Generated by Django 5.2.17 on 2026-09-12 12:02

from django.db import migrations, models

import apps.core.models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_commune_public_base_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="commune",
            name="favicon",
            field=models.FileField(
                blank=True,
                default="",
                upload_to=apps.core.models.commune_favicon_path,
                verbose_name="favicon",
            ),
        ),
        migrations.AddField(
            model_name="commune",
            name="favicon_content_hash",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="commune",
            name="favicon_content_type",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="commune",
            name="logo",
            field=models.FileField(
                blank=True,
                default="",
                upload_to=apps.core.models.commune_logo_path,
                verbose_name="logo",
            ),
        ),
        migrations.AddField(
            model_name="commune",
            name="logo_content_hash",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="commune",
            name="logo_content_type",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
    ]
