# SPDX-License-Identifier: 0BSD
# Generated by Django 5.2.17 on 2026-09-16 00:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_commune_branding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commune",
            name="data_protection_referent",
            field=models.CharField(
                help_text="Personne ou service à qui les électeurs adressent leurs demandes d'accès, de rectification et d'effacement.",
                max_length=200,
                verbose_name="référent données personnelles",
            ),
        ),
    ]
