# SPDX-License-Identifier: 0BSD
# Generated by Django 5.2.17 on 2026-09-16 00:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_alter_commune_data_protection_referent"),
    ]

    operations = [
        migrations.AddField(
            model_name="commune",
            name="legal_notice",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Affichées en pied de page de chaque page : éditeur du site, hébergeur, etc. Laissez vide pour n'afficher aucune mention.",
                verbose_name="mentions légales",
            ),
        ),
    ]
