# SPDX-License-Identifier: 0BSD
# Generated by Django 5.2.17 on 2026-09-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_commune_legal_notice"),
    ]

    operations = [
        migrations.AddField(
            model_name="commune",
            name="show_name_with_logo",
            field=models.BooleanField(default=False, verbose_name="afficher le nom à côté du logo"),
        ),
    ]
