# SPDX-License-Identifier: 0BSD
# Generated by Django 5.2.17 on 2026-09-18 16:20

from django.db import migrations, models

import apps.core.models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_commune_show_name_with_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="commune",
            name="logo_dark",
            field=models.FileField(
                blank=True,
                default="",
                upload_to=apps.core.models.commune_logo_dark_path,
                verbose_name="logo (thème sombre)",
            ),
        ),
        migrations.AddField(
            model_name="commune",
            name="logo_dark_content_hash",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="commune",
            name="logo_dark_content_type",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
    ]
