# Generated by Django 5.2.17 on 2026-09-07 19:19

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ballot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("ballot_hash", models.BinaryField(blank=True, max_length=32, null=True)),
                ("tracking_code", models.CharField(max_length=10)),
                ("version", models.PositiveIntegerField(default=1)),
                ("ranking", models.JSONField(default=list)),
                (
                    "source",
                    models.CharField(
                        choices=[("online", "en ligne"), ("paper", "papier")], max_length=10
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("live", "courant"),
                            ("superseded", "remplacé"),
                            ("deleted", "supprimé"),
                            ("pending_countersign", "en attente de contreseing"),
                        ],
                        default="live",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "bulletin",
                "verbose_name_plural": "bulletins",
            },
        ),
        migrations.CreateModel(
            name="PaperBallotLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("language", models.CharField(blank=True, max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
