# Generated by Django 5.2.17 on 2026-09-07 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ballots", "0001_initial"),
        ("elections", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ballot",
            name="poll",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ballots",
                to="elections.poll",
            ),
        ),
        migrations.AddField(
            model_name="paperballotlink",
            name="ballot",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paper_link",
                to="ballots.ballot",
            ),
        ),
        migrations.AddField(
            model_name="paperballotlink",
            name="countersigned_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="countersigned_ballots",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="paperballotlink",
            name="operator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="keyed_ballots",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="paperballotlink",
            name="poll",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paper_links",
                to="elections.poll",
            ),
        ),
        migrations.AddIndex(
            model_name="ballot",
            index=models.Index(fields=["poll", "status"], name="ballots_bal_poll_id_23f1be_idx"),
        ),
        migrations.AddIndex(
            model_name="ballot",
            index=models.Index(
                fields=["poll", "ballot_hash"], name="ballots_bal_poll_id_dea50e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="ballot",
            constraint=models.UniqueConstraint(
                fields=("poll", "tracking_code"), name="uniq_ballot_poll_tracking_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="ballot",
            constraint=models.UniqueConstraint(
                fields=("poll", "tracking_code", "version"), name="uniq_ballot_version"
            ),
        ),
        migrations.AddIndex(
            model_name="paperballotlink",
            index=models.Index(fields=["poll", "nne"], name="ballots_pap_poll_id_db9383_idx"),
        ),
    ]
