# Generated by Django 5.2.17 on 2026-09-17 18:55

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ballots", "0002_initial"),
        ("elections", "0008_option_details_and_images"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReconciliationRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("forms_retained_count", models.PositiveIntegerField()),
                ("recorded_ballots_count", models.PositiveIntegerField()),
                ("note", models.TextField(blank=True)),
                ("signed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "poll",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reconciliation_record",
                        to="elections.poll",
                    ),
                ),
                (
                    "signed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="signed_reconciliations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "procès-verbal de rapprochement",
                "verbose_name_plural": "procès-verbaux de rapprochement",
            },
        ),
    ]
