# Generated by Django 5.2.17 on 2026-09-07 19:19

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.core.crypto


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Poll",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title_i18n", models.JSONField(default=dict, verbose_name="titre")),
                ("description_i18n", models.JSONField(default=dict, verbose_name="description")),
                ("languages", models.JSONField(default=list)),
                ("opens_at", models.DateTimeField(verbose_name="ouverture")),
                ("closes_at", models.DateTimeField(verbose_name="clôture")),
                (
                    "paper_entry_deadline",
                    models.DateTimeField(
                        help_text="≥ clôture ; par défaut égale à elle (§6.4).",
                        verbose_name="fin de saisie des bulletins papier",
                    ),
                ),
                ("timezone", models.CharField(default="Europe/Paris", max_length=64)),
                (
                    "tally_method",
                    models.CharField(
                        choices=[
                            ("schulze", "Schulze"),
                            ("plurality", "majoritaire"),
                            ("approval", "par assentiment"),
                        ],
                        default="schulze",
                        max_length=20,
                    ),
                ),
                ("tally_method_version", models.CharField(default="1", max_length=20)),
                ("require_complete_ranking", models.BooleanField(default=True)),
                ("allow_ties_in_ballot", models.BooleanField(default=False)),
                (
                    "tiebreak_rule",
                    models.CharField(
                        choices=[
                            ("computed", "tirage au sort calculé"),
                            ("physical", "tirage au sort physique"),
                        ],
                        default="computed",
                        max_length=20,
                    ),
                ),
                ("opening_seed", models.BinaryField(blank=True, max_length=32, null=True)),
                (
                    "token_salt",
                    models.BinaryField(default=apps.core.crypto.new_token_salt, max_length=32),
                ),
                ("paper_requires_signed_form", models.BooleanField(default=False)),
                ("paper_requires_countersign", models.BooleanField(default=False)),
                ("paper_requires_reconciliation", models.BooleanField(default=False)),
                ("allow_ballot_modification", models.BooleanField(default=True)),
                ("show_live_participation", models.BooleanField(default=False)),
                ("is_sandbox", models.BooleanField(default=False)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "brouillon"),
                            ("open", "ouvert"),
                            ("closed", "clos"),
                            ("published", "publié"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("closure_hash", models.BinaryField(blank=True, max_length=32, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("frozen_counts", models.JSONField(blank=True, default=dict)),
                ("closure_override_reason", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "scrutin",
                "verbose_name_plural": "scrutins",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("closes_at__gt", models.F("opens_at"))),
                        name="poll_closes_after_opens",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("paper_entry_deadline__gte", models.F("closes_at"))),
                        name="poll_paper_deadline_after_closes",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RollImport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("file_sha256", models.BinaryField(max_length=32)),
                ("row_count", models.PositiveIntegerField()),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
                (
                    "imported_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkingRollEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("last_name", models.CharField(max_length=200)),
                ("first_names", models.CharField(max_length=200)),
                ("nne", models.CharField(max_length=9, unique=True)),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["last_name"], name="elections_w_last_na_15bc43_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="PollOption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("option_id", models.SlugField()),
                ("label_i18n", models.JSONField(default=dict)),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "poll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="elections.poll",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "option_id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("poll", "option_id"), name="uniq_poll_option_id"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RollEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("last_name", models.CharField(max_length=200)),
                ("first_names", models.CharField(max_length=200)),
                ("nne", models.CharField(max_length=9)),
                (
                    "poll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roll_entries",
                        to="elections.poll",
                    ),
                ),
            ],
            options={
                "verbose_name": "électeur inscrit",
                "verbose_name_plural": "liste électorale figée",
                "indexes": [
                    models.Index(
                        fields=["poll", "last_name"], name="elections_r_poll_id_7ffa56_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("poll", "nne"), name="uniq_rollentry_poll_nne")
                ],
            },
        ),
    ]
