# SPDX-License-Identifier: 0BSD
# Generated by Django 5.2.17 on 2026-09-11 08:06

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.elections.models


class Migration(migrations.Migration):
    dependencies = [
        ("elections", "0003_poll_physical_tiebreak_order"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PollTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True, verbose_name="nom")),
                (
                    "tally_method",
                    models.CharField(
                        choices=[
                            ("schulze", "Schulze"),
                            ("plurality", "majoritaire"),
                            ("approval", "par assentiment"),
                        ],
                        default="schulze",
                        max_length=20,
                    ),
                ),
                ("tally_method_version", models.CharField(default="1", max_length=20)),
                ("require_complete_ranking", models.BooleanField(default=True)),
                ("allow_ties_in_ballot", models.BooleanField(default=False)),
                (
                    "tiebreak_rule",
                    models.CharField(
                        choices=[
                            ("computed", "tirage au sort calculé"),
                            ("physical", "tirage au sort physique"),
                        ],
                        default="computed",
                        max_length=20,
                    ),
                ),
                ("paper_requires_signed_form", models.BooleanField(default=False)),
                ("paper_requires_countersign", models.BooleanField(default=False)),
                ("paper_requires_reconciliation", models.BooleanField(default=False)),
                ("allow_ballot_modification", models.BooleanField(default=True)),
                (
                    "eligible_list_types",
                    models.JSONField(default=apps.elections.models.default_eligible_list_types),
                ),
                ("languages", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="poll_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "modèle de scrutin",
                "verbose_name_plural": "modèles de scrutin",
                "ordering": ["name"],
            },
        ),
    ]
