; SPDX-License-Identifier: 0BSD
; Copy to inventory.ini and edit. Secrets come from ansible-vault, never here.
[polls]
vote.exemple-commune.fr

[polls:vars]
polls_domain=vote.exemple-commune.fr
polls_admin_email=mairie@exemple-commune.fr
polls_smoke_test_email=informatique@exemple-commune.fr
polls_scheduler=cron
